Repository NexoEngine/game-engine, pull requests merged in 2025-09, with the labels that each got.

#396 fix: warnings on msvc compiler
  CMakeLists.txt
  common/Error.hpp
  common/Timestep.hpp
  editor/src/DocumentWindows/EditorScene/Init.cpp
  editor/src/DocumentWindows/SceneTreeWindow/Update.cpp
  editor/src/DocumentWindows/TestWindow/Parser.cpp
  editor/src/DocumentWindows/TestWindow/Shutdown.cpp
  editor/src/Editor.cpp
  editor/src/backends/ImGuiBackend.cpp
  engine/src/core/event/Input.cpp
  engine/src/ecs/ComponentArray.hpp
  engine/src/ecs/ECSExceptions.hpp
  engine/src/ecs/Group.hpp
  engine/src/ecs/GroupSystem.hpp
  engine/src/renderer/Buffer.cpp
  engine/src/renderer/Buffer.hpp
  engine/src/renderer/Framebuffer.cpp
  engine/src/renderer/RenderCommand.hpp
  engine/src/renderer/RendererAPI.hpp
  engine/src/renderer/RendererExceptions.hpp
  engine/src/renderer/Shader.cpp
  engine/src/renderer/Shader.hpp
  engine/src/renderer/ShaderStorageBuffer.cpp
  engine/src/renderer/ShaderStorageBuffer.hpp
  engine/src/renderer/Texture.cpp
  engine/src/renderer/Texture.hpp
  engine/src/renderer/VertexArray.cpp
  engine/src/renderer/Window.cpp
  engine/src/renderer/opengl/OpenGlBuffer.cpp
  engine/src/renderer/opengl/OpenGlBuffer.hpp
  engine/src/renderer/opengl/OpenGlFramebuffer.hpp
  engine/src/renderer/opengl/OpenGlRendererAPI.hpp
  engine/src/renderer/opengl/OpenGlRendererApi.cpp
  engine/src/renderer/opengl/OpenGlShader.cpp
  engine/src/renderer/opengl/OpenGlShaderStorageBuffer.cpp
  engine/src/renderer/opengl/OpenGlShaderStorageBuffer.hpp
  engine/src/renderer/opengl/OpenGlTexture2D.cpp
  engine/src/renderer/opengl/OpenGlTexture2D.hpp
  engine/src/renderer/primitives/Cylinder.cpp
  engine/src/scripting/native/NativeApi.cpp
  engine/src/scripting/native/NativeApi.hpp
  engine/src/systems/PhysicsSystem.cpp
  engine/src/systems/PhysicsSystem.hpp
  examples/ecs/exampleBasic.cpp
  tests/CMakeLists.txt
  tests/ecs/Components.test.cpp
  tests/ecs/Exceptions.test.cpp
  tests/engine/assets/AssetLocation.test.cpp
  tests/renderer/Buffer.test.cpp
  tests/renderer/Framebuffer.test.cpp
  tests/renderer/Pipeline.test.cpp
  tests/renderer/contexts/opengl.hpp
Labels: bug

#421 feat: thumbnail previews
  editor/src/DocumentWindows/AssetManager/Show.cpp
  editor/src/context/ThumbnailCache.cpp
  editor/src/context/ThumbnailCache.hpp
  editor/src/utils/ScenePreview.cpp
Labels: enhancement, editor

#414 feat: asset manager right click menu
  editor/CMakeLists.txt
  editor/src/DocumentWindows/AssetManager/AssetGrid.cpp
  editor/src/DocumentWindows/AssetManager/AssetManagerWindow.hpp
  editor/src/DocumentWindows/AssetManager/AssetsPopupUtils.cpp
  editor/src/DocumentWindows/AssetManager/DragDrop.cpp
  editor/src/DocumentWindows/AssetManager/FileDrop.cpp
  editor/src/DocumentWindows/AssetManager/FolderCreation.cpp
  editor/src/DocumentWindows/AssetManager/FolderManager.cpp
  editor/src/DocumentWindows/AssetManager/FolderManager.hpp
  editor/src/DocumentWindows/AssetManager/FolderTree.cpp
  editor/src/DocumentWindows/AssetManager/FoldersPopupUtils.cpp
  editor/src/DocumentWindows/AssetManager/Init.cpp
  editor/src/DocumentWindows/AssetManager/RightClickUtils.cpp
  editor/src/DocumentWindows/AssetManager/Selection.cpp
  editor/src/DocumentWindows/AssetManager/Show.cpp
  editor/src/DocumentWindows/AssetManager/Shutdown.cpp
  editor/src/DocumentWindows/AssetManager/Update.cpp
  editor/src/DocumentWindows/AssetManager/Utils.cpp
  editor/src/DocumentWindows/EditorScene/Show.cpp
  editor/src/DocumentWindows/EditorScene/Toolbar.cpp
  editor/src/DocumentWindows/EntityProperties/MaterialProperty.cpp
  editor/src/DocumentWindows/PopupManager.cpp
  editor/src/DocumentWindows/PopupManager.hpp
  editor/src/DocumentWindows/SceneTreeWindow/Show.cpp
  editor/src/ImNexo/Elements.cpp
  editor/src/ImNexo/Elements.hpp
  engine/src/assets/Asset.hpp
  engine/src/assets/AssetCatalog.cpp
  engine/src/assets/AssetCatalog.hpp
  engine/src/assets/AssetLocation.hpp
Labels: enhancement
