Repository NexoEngine/game-engine, pull requests merged in 2025-07, with the labels that each got.

#133 feat: add primitives
  .idea/cmake.xml
  editor/CMakeLists.txt
  editor/main.cpp
  editor/src/ADocumentWindow.hpp
  editor/src/DocumentWindows/EditorScene/EditorScene.hpp
  editor/src/DocumentWindows/EditorScene/Init.cpp
  editor/src/DocumentWindows/EditorScene/Show.cpp
  editor/src/DocumentWindows/EditorScene/Toolbar.cpp
  editor/src/DocumentWindows/EntityProperties/RenderProperty.cpp
  editor/src/DocumentWindows/EntityProperties/RenderProperty.hpp
  editor/src/DocumentWindows/Primitive.hpp
  editor/src/DocumentWindows/PrimitiveWindow/Init.cpp
  editor/src/DocumentWindows/PrimitiveWindow/PrimitiveWindow.hpp
  editor/src/DocumentWindows/PrimitiveWindow/Show.cpp
  editor/src/DocumentWindows/PrimitiveWindow/Shutdown.cpp
  editor/src/DocumentWindows/PrimitiveWindow/Update.cpp
  editor/src/DocumentWindows/SceneTreeWindow/SceneTreeWindow.hpp
  editor/src/DocumentWindows/SceneTreeWindow/Show.cpp
  editor/src/ImNexo/Widgets.cpp
  editor/src/ImNexo/Widgets.hpp
  editor/src/utils/FileSystem.hpp
  engine/CMakeLists.txt
  engine/src/EntityFactory3D.cpp
  engine/src/EntityFactory3D.hpp
  engine/src/renderer/Renderer3D.hpp
  engine/src/renderer/Shader.hpp
  engine/src/renderer/primitives/Billboard.cpp
  engine/src/renderer/primitives/Cube.cpp
  engine/src/renderer/primitives/Cylinder.cpp
  engine/src/renderer/primitives/Pyramid.cpp
  engine/src/renderer/primitives/Sphere.cpp
  engine/src/renderer/primitives/Tetrahedron.cpp
  tests/renderer/CMakeLists.txt
Labels: enhancement

#333 feat: game window (When Pressing play button)
  editor/CMakeLists.txt
  editor/main.cpp
  editor/src/ADocumentWindow.hpp
  editor/src/DocumentWindows/EditorScene/EditorScene.hpp
  editor/src/DocumentWindows/EditorScene/Init.cpp
  editor/src/DocumentWindows/EditorScene/Show.cpp
  editor/src/DocumentWindows/EditorScene/Toolbar.cpp
  editor/src/DocumentWindows/GameWindow/GameWindow.cpp
  editor/src/DocumentWindows/GameWindow/GameWindow.hpp
  editor/src/DocumentWindows/GameWindow/Setup.cpp
  editor/src/DocumentWindows/GameWindow/Show.cpp
  editor/src/DocumentWindows/GameWindow/Update.cpp
Labels: enhancement

#355 feat: implement NEXO API in C# lib
  engine/src/Application.cpp
  engine/src/ecs/Coordinator.cpp
  engine/src/ecs/Coordinator.hpp
  engine/src/scripting/managed/CMakeLists.txt
  engine/src/scripting/managed/NativeComponents.cs
  engine/src/scripting/managed/NativeInterop.cs
  engine/src/scripting/native/NativeApi.cpp
  engine/src/scripting/native/NativeApi.hpp
Labels: enhancement

#352 feat: add custom components to .NET scripts
  engine/CMakeLists.txt
  engine/src/ecs/ComponentArray.cpp
  engine/src/ecs/ComponentArray.hpp
  engine/src/ecs/Components.hpp
  engine/src/ecs/Coordinator.hpp
  engine/src/ecs/Definitions.hpp
  engine/src/scripting/managed/CMakeLists.txt
  engine/src/scripting/managed/Components/ComponentBase.cs
  engine/src/scripting/managed/Logger.cs
  engine/src/scripting/managed/NativeInterop.cs
  engine/src/scripting/managed/Scripts/CubeSystem.cs
  engine/src/scripting/managed/Systems/SystemBase.cs
  engine/src/scripting/managed/Systems/WorldState.cs
  engine/src/scripting/native/ManagedApi.hpp
  engine/src/scripting/native/NativeApi.cpp
  engine/src/scripting/native/NativeApi.hpp
  engine/src/scripting/native/Scripting.cpp
  engine/src/systems/ScriptingSystem.cpp
Labels: enhancement

#382 feat: link physics with 3D primitives and scripting
  .idea/cmake.xml
  editor/src/DocumentWindows/EditorScene/Init.cpp
  editor/src/utils/FileSystem.cpp
  engine/src/Application.cpp
  engine/src/EntityFactory3D.cpp
  engine/src/components/Light.hpp
  engine/src/ecs/ComponentArray.hpp
  engine/src/ecs/Components.hpp
  engine/src/ecs/Coordinator.hpp
  engine/src/renderer/primitives/Tetrahedron.cpp
  engine/src/scripting/managed/CMakeLists.txt
  engine/src/scripting/managed/Components/Camera.cs
  engine/src/scripting/managed/Components/PhysicsBodyComponent.cs
  engine/src/scripting/managed/Components/PhysicsEnums.cs
  engine/src/scripting/managed/Components/Scene.cs
  engine/src/scripting/managed/Components/Uuid.cs
  engine/src/scripting/managed/NativeInterop.cs
  engine/src/scripting/native/NativeApi.cpp
  engine/src/scripting/native/NativeApi.hpp
  engine/src/systems/PhysicsSystem.cpp
  engine/src/systems/PhysicsSystem.hpp
  engine/src/systems/ScriptingSystem.cpp
  resources/shaders/phong.glsl
  tests/engine/physics/PhysicsSystem.test.cpp
  tests/renderer/Renderer3D.test.cpp
Labels: enhancement, physics, scripting

#344 fix: front-end for materials assets
  editor/CMakeLists.txt
  editor/src/DocumentWindows/AssetManager/AssetManagerWindow.hpp
  editor/src/DocumentWindows/AssetManager/FolderTree.cpp
  editor/src/DocumentWindows/AssetManager/Init.cpp
  editor/src/DocumentWindows/AssetManager/Show.cpp
  editor/src/DocumentWindows/EditorScene/Init.cpp
  editor/src/DocumentWindows/EntityProperties/MaterialProperty.cpp
  editor/src/DocumentWindows/EntityProperties/MaterialProperty.hpp
  editor/src/DocumentWindows/EntityProperties/RenderProperty.cpp
  editor/src/DocumentWindows/EntityProperties/RenderProperty.hpp
  editor/src/DocumentWindows/InspectorWindow/Init.cpp
  editor/src/DocumentWindows/InspectorWindow/InspectorWindow.hpp
  editor/src/DocumentWindows/MaterialInspector/MaterialInspector.hpp
  editor/src/DocumentWindows/MaterialInspector/Show.cpp
  editor/src/DocumentWindows/SceneTreeWindow/Update.cpp
  editor/src/ImNexo/EntityProperties.cpp
  editor/src/ImNexo/Panels.cpp
  editor/src/ImNexo/Panels.hpp
  editor/src/context/ThumbnailCache.cpp
  editor/src/context/ThumbnailCache.hpp
  editor/src/utils/EditorProps.cpp
  engine/CMakeLists.txt
  engine/src/EntityFactory3D.cpp
  engine/src/assets/Assets/Model/ModelImporter.cpp
  engine/src/assets/Assets/Model/ModelImporter.hpp
  engine/src/components/BillboardMesh.hpp
  engine/src/components/Parent.hpp
  engine/src/components/Render.hpp
  engine/src/components/Transform.cpp
  engine/src/components/Transform.hpp
  engine/src/core/scene/Scene.cpp
  engine/src/renderPasses/ForwardPass.hpp
  engine/src/renderPasses/GridPass.hpp
  engine/src/renderPasses/MaskPass.hpp
  engine/src/renderPasses/OutlinePass.hpp
  engine/src/renderer/Attributes.hpp
  engine/src/renderer/DrawCommand.hpp
  engine/src/renderer/Shader.cpp
  engine/src/renderer/ShaderLibrary.cpp
  engine/src/renderer/ShaderLibrary.hpp
  engine/src/renderer/UniformCache.cpp
  engine/src/renderer/UniformCache.hpp
  engine/src/renderer/opengl/OpenGlFramebuffer.cpp
  engine/src/renderer/opengl/OpenGlRendererApi.cpp
  engine/src/renderer/opengl/OpenGlShader.cpp
  engine/src/renderer/opengl/OpenGlShaderReflection.cpp
  engine/src/systems/TransformHierarchySystem.cpp
  tests/renderer/Pipeline.test.cpp
  tests/renderer/Renderer3D.test.cpp
Labels: enhancement

#393 hotfix: codeql workflow
  .github/workflows/codeql.yml
Labels: enhancement

#389 fix: compilation warning
  editor/src/DocumentWindows/EditorScene/Init.cpp
  editor/src/Editor.cpp
  editor/src/utils/FileSystem.cpp
  engine/src/Application.cpp
  engine/src/ecs/ComponentArray.hpp
  engine/src/renderer/primitives/Cylinder.cpp
  engine/src/renderer/primitives/Sphere.cpp
  engine/src/scripting/native/NativeApi.cpp
  examples/ecs/exampleBasic.cpp
  tests/renderer/Buffer.test.cpp
  tests/renderer/VertexArray.test.cpp
Labels: bug, enhancement
